[package]
name = "ws-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.40.0", features = ["full"] }
scraper = "0.20.0"
open = "5"
thirtyfour = { version = "0.34.0", features = ["native-tls"] }